export class ShipOut {  
    rowId: number = 0;
    addressID:any;
    createdBy: number = 0;
    createdDate: any;
    updatedBy: number = 0;
    updatedDate: any;
    customerId: number = 0;
    locID: number = 0;
    customerName: string = '';
    streetAddress: string = '';
    from: string = '';
    fromAddress: string = '';
    carrier: string = '';
    truck: string = '';
    make: string = '';
    model: string = '';
    driverName: string = '';
    note: string = '';
    driverlicense:string = '';
    licenseplate:string = '';
    // trailer1: string = '';
    // trailer2: string = '';
    // container: string = '';
    // seal: string = '';
    // booking: string = '';
    // vessels: string = '';
    // chasis: string = '';
    // packSlip: string = '';
    // reference: string = '';
    totalGross: number = 0;
    totalTare: number = 0;
    totalNet: number = 0;
    totalPrice:number=0;
    totalAmount:number=0;
    currencyCode: string = '';
    currencySymbol: string = '';
    SalesOrderID: number = 0;
    SalesOrderMaterialID: number = 0;
    shipoutmaterial: any;
}
