export class TicketItem {
     localRowId: number = 0;
     isCODupdated: boolean = false;
     rowId: number = 0;
     createdBy: number = 0;
     createdDate: any;
     updatedBy: number = 0;
     updatedDate: any;
     count: number = 0.00;
     gross: number = 0.00;
     tare: number = 0.00;
     net: number = 0.00;
     price: number = 0.00;
     amount: number = 0.00;
     ticketID: number = 0;
     transactionDate: any;
     materialName: string = '';
     groupName: string = '';
     materialId: number = 0.00;
     imagePath: string = '';
     materialNote: string = '';
     codNote: string = '';
     isHold: boolean = false;
     dealerPrice: any = null;
     isAdjusmentSet: any = null;
     concatAdjustments: string = '';
     isCOD: any = null;
     isCODDone: any = null;
     isCRV: boolean = false;
     codDescription: string = '';
     codImagePath: string = '';
}
